### ISSUE TITLE
Sample for a dashboard

### ISSUE THREAD

**Issue by fasteddys** [statiqdev/CleanBlog#17]
Hello can you share a sample for a dashboard or a business app, where we can tailor the _partials in the input templates for tables, cards etc.

**Comment by daveaglick** [comment]
I'm sorry, but I don't have the time to work up an entirely new sample for this kind of scenario - at least not at this time. Note that the CleanBlog theme probably isn't the best starting point for dashboard-oriented site anyway. You'll likely want to start with a more appropriate generic template like [one of these](https://wrapbootstrap.com/category/templates/admin-templates) and then adapt it for use with Statiq.
